FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY immigration_requirements.txt .
RUN pip install --no-cache-dir -r immigration_requirements.txt

COPY immigration/ ./immigration/
COPY immigration_main.py .

CMD ["python", "-u", "immigration_main.py"]
